
settings:
  content:
    merge: true

media:
  - name: images
    label: Images
    input: content/images
    output: /content/images
    extensions:
      - jpg
      - jpeg
      - png
      - webp
      - gif
    categories:
      - image

  - name: videos
    label: Videos
    input: content/videos
    output: /content/videos
    extensions:
      - mp4
      - webm
      - mov
      - m4v
    categories:
      - video

  - name: audio
    label: Audio
    input: content/audio
    output: /content/audio
    extensions:
      - mp3
      - wav
      - ogg
      - m4a
      - aac
    categories:
      - audio

  - name: files
    label: Files
    input: content/files
    output: /content/files
    extensions:
      - pdf
      - zip
      - epub
      - doc
      - docx
    categories:
      - document

content:
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    filename: "{primary}.md"

    fields:
      - name: title
        label: Title
        type: string

      - name: cover
        label: Cover Image
        type: image
        options:
          media: images
          extensions:
            - jpg
            - jpeg
            - png
            - webp
            - gif

      - name: credits
        label: Credits
        type: text

      - name: video
        label: Video
        type: file
        options:
          media: videos
          extensions:
            - mp4
            - webm
            - mov
            - m4v

      - name: audio
        label: Audio
        type: file
        options:
          media: audio
          extensions:
            - mp3
            - wav
            - ogg
            - m4a
            - aac

      - name: downloads
        label: Downloads
        type: file
        options:
          media: files
          extensions:
            - pdf
            - zip
            - epub
            - doc
            - docx
          multiple:
            max: 10

      - name: body
        label: Article
        type: rich-text
        options:
          media: images
          extensions:
            - jpg
            - jpeg
            - png
            - webp
            - gif
          switcher: true

