```yaml
media:
  - name: images
    label: Images
    input: content/images
    output: /content/images

content:
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    filename: "{primary}.md"

    fields:
      - name: title
        label: Title
        type: string

      - name: cover
        label: Cover Image
        type: image
        options:
          media: images

      - name: body
        label: Article
        type: rich-text
        options:
          media: images
```

